spring.application.name=demo
server.port=8080
spring.datasource.url=jdbc:h2:mem:bankingdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
rapidapi.key=1e17f923abmsh8877f04bae92a3ap13dc4cjsnd40b8f030c86

# //alphavantage.api.key=YOUR_API_KEY_HERE

